name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Build Project/Solution
      run: dotnet build
